### ISSUE TITLE
Не доступен хост dr2.rbkmoney.com

### ISSUE THREAD

**Issue by TakT** [rbkmoney/fraudbusters#65]
Не доступен хост dr2.rbkmoney.com

![image](https://user-images.githubusercontent.com/2765385/77233815-49959500-6bd4-11ea-9068-30584a6103bb.png)

Как следствие, не поднимается докер
![image](https://user-images.githubusercontent.com/2765385/77233823-54e8c080-6bd4-11ea-89cf-42b704dce0d2.png)

**Comment by strug** [comment]
> Не доступен хост dr2.rbkmoney.com
> 
> ![image](https://user-images.githubusercontent.com/2765385/77233815-49959500-6bd4-11ea-9068-30584a6103bb.png)
> 
> Как следствие, не поднимается докер
> ![image](https://user-images.githubusercontent.com/2765385/77233823-54e8c080-6bd4-11ea-89cf-42b704dce0d2.png)

Сейчас проводим работы по выносу всей инфраструктуры на доступные всем сервера, про проблему знаем и будем ее решать

**Comment by tolkonepiu** [comment]
@TakT перевели проект на **docker hub**. Получить image можно командой:
```
docker pull rbkmoney/fraudbusters:deea70133e6de41b6a46194b210ae7c3b313a1a8
```
